### ISSUE TITLE
Need to clean up multiple Github repos called CogControl

### ISSUE THREAD

**Issue by kristabh** [kbhlab/CogControl#2]
@hilary-rose will take care of?

**Comment by hilary-rose** [comment]
I deleted my hilary-rose/CogControl repo. I think the other two will have to be removed by @kristabh and @Pouriliaei as the account holders. However, since the KBH Lab version is forked from yours, will removing the original(s) affect the KBH Lab one?

**Comment by kristabh** [comment]
Should be fine.  The different forks exist independently.  I have changed the name of mine to be CogControl-OLD just not to get mixed up. @Pouriliaei you might want to change the name of your original repository too.  I suppose eventually we could merge this new branch back into ours, if we wanted to.
